# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: foobar
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: test

# "service" is the name of this project. This will also be added to your AWS resource names.
service: pizzaApp

provider:
  name: aws
  runtime: nodejs20.x

functions:
  newOrder:
    handler: handler.newOrder
    events:
      - httpApi:
          path: /order
          method: post
  getOrder:
    handler: handler.getOrder
    events:
      - httpApi:
          path: /order/{orderId}
          method: get
  prepOrder: 
    handler: handler.prepOrder
    events:
      - sqs:
          arn: 
            Fn::GetAtt: [PendingOrderQueue, Arn]
          batchSize: 1

resources: # Cloudformation template syntax
  Resources:
    PendingOrderQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: pendingOrderQueue